# Generated by Django 6.0 on 2026-01-10 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="buyer",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="coupon",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="seller",
        ),
        migrations.RenameField(
            model_name="coupon",
            old_name="title",
            new_name="code",
        ),
        migrations.RemoveField(
            model_name="coupon",
            name="brand",
        ),
        migrations.RemoveField(
            model_name="coupon",
            name="coupon_code",
        ),
        migrations.RemoveField(
            model_name="coupon",
            name="discount",
        ),
        migrations.RemoveField(
            model_name="coupon",
            name="expiry_date",
        ),
        migrations.DeleteModel(
            name="Review",
        ),
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
