# Generated by Django 6.0 on 2026-01-11 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0003_transaction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="buyer",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="coupon",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="seller",
        ),
        migrations.AddField(
            model_name="transaction",
            name="description",
            field=models.CharField(default="System generated", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("CREDIT", "Credit"), ("DEBIT", "Debit")],
                default="System generated",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="coupon",
            name="category",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="code",
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coupon",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="coupons.coupon"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
